### ISSUE TITLE
Many versions of CWS, POS etc.

### ISSUE THREAD

**Issue by GabrielLin** [Pelhans/ZNLP#1]
It seems that this repository is duplicative with your other CWS, POS etc. repositories. In my opinion, it is hard to maintain and will be a little difficult for other users to follow up. Could you please just link projects or just maintain one repository? Thanks.

**Comment by Pelhans** [comment]
I totaly agree with you, I would reomve these three independent repos and keep updating these parts in ZNLP. Thanks~

**Comment by GabrielLin** [comment]
Thanks.
