### ISSUE TITLE
No such file or directory: 'common/ZNLP/znlp/../lexical_analysis/ner_blstm/data/pkl/dict_data.pkl

### ISSUE THREAD

**Issue by jojolin** [Pelhans/ZNLP#2]
Hello! 当我运行下面命令时出现了上面的异常。请问dict_data.pkl是啥，谢谢！
from znlp import ner

**Comment by Pelhans** [comment]
感谢您的反馈。github上只存放了代码，与之相关的模型和数据需要自己生成，具体生成方式可以参考各个模块对应的文件夹，如ner的化就是ZNLP/lexical_analysis/ner_blstm/readme.md,在生成数据并训练完成后就可以按照示例导入了。    
utils/get_pickle.py 用来将词和标签转换为id并存为pkl。参数 dev 和 test 文件对应于生成验证和测试数据    
bin/ner_blstm.py用来训练模型
