### ISSUE TITLE
请教一个关于自然语言数据抽取的问题

### ISSUE THREAD

**Issue by neohope** [Pelhans/ZNLP#3]
我是从您的网站找过来的，本来想在网站上问一下，但一直没能登录成功，只好在这边问啦。

在近期的项目上，遇到了需要从大段自然语言中抽取数据的需求。我现在可以搞定分词、词性标定、并通过正则进行部分数据抽取。但由于语言并不规范，抽取规则太多，很难完全通过正则表达式抽取数据。

看了很多资料，大家推荐用深度学习的。但找了一大圈，没找到合适的项目或例子。您能帮忙推荐一个吗？或者有其他建议吗？感谢！

**Comment by Pelhans** [comment]
做项目的话，还是用前人做好的工具比较合适，它们的训练数据和速度都不是自己写的能比得了的。我个人使用过 LTP 和 斯坦福的分析工具，都还蛮好用的。
